import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import CardUser from '../components/cardUser'
import Link from 'next/link'

export async function getServerSideProps() {
  const res = await fetch('https://jherr-pokemon.s3.us-west-1.amazonaws.com/index.json')
  const data = await res.json()
  return {
    props: {
      pokemon: data
    }
  }
}

export default function Home({ pokemon }) {
  return (
    <div className='container'>
      <Head>
        <title>Julio Iglesias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossOrigin="anonymous" />
      </Head>

      <div className={styles.grid}>
        {pokemon.length === 0 ? (
          <div class="d-flex justify-content-center">
            <div class="spinner-border" role="status">
              <span class="visually-hidden">Loading...</span>
            </div>
          </div>
        ) : (
          
            pokemon.map((pokemon) => (
              <div className={styles.card} key={pokemon.id}>
                <Link href={`/pokemon/${pokemon.id}`}>
                  <a>
                    <img src={`https://jherr-pokemon.s3.us-west-1.amazonaws.com/${pokemon.image}`}
                      alt={pokemon.name} />
                    <h5>{pokemon.name}</h5>
                  </a>
                </Link>
              </div>
            ))
        )}

      </div>

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossOrigin="anonymous" />

    </div>
  )
}
